[package]
name = "day-9-mirage-maintenance"
version = "0.1.0"
edition = "2021"

[dependencies]
dhat.workspace = true
anyhow.workspace = true
rstest.workspace = true
itertools.workspace = true

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false
